overrides:
  zbkc:
    conf:
      global:
        ms die on skipped message: false
tasks:
- install:
    branch: dumpling
- zbkc:
- parallel:
   - user-workload
   - kclient-workload
user-workload:
  sequential:
  - zbkc-fuse: [client.0]
  - workunit:
      clients:
         client.0:
           - suites/blogbench.sh
kclient-workload:
  sequential:
  - kclient: [client.1]
  - workunit:
      clients:
         client.1:
           - kernel_untar_build.sh
