# this runs s3tests against rgw, using mod_fastcgi
roles:
- [mon.a, mon.c, osd.0, osd.1, osd.2, client.0]
- [mon.b, osd.3, osd.4, osd.5, client.1]

tasks:
- install:
    branch: master
- zbkc:
- rgw: [client.0]
- s3tests:
    client.0:
      rgw_server: client.0
      force-branch: master
overrides:
  zbkc:
    fs: xfs
    conf:
      client:
        debug rgw: 20
        rgw lc debug interval: 10
  rgw:
    ec-data-pool: false
    frontend: apache
