overrides:
  zbkc:
    conf:
      client.0:
        admin socket: /var/run/zbkc/zbkc-$name.asok
tasks:
- radosbench:
    clients: [client.0]
    time: 60
- admin_socket:
    client.0:
      objecter_requests:
        test: "http://git.zbkc.com/?p=zbkc.git;a=blob_plain;f=src/test/admin_socket/objecter_requests;hb={branch}"
