overrides:
  zbkc:
    conf:
      osd:
        filestore flush min: 0
      mds:
        debug ms: 1
        debug mds: 20
tasks:
- zbkc-fuse:
- workunit:
    clients:
      all:
        - suites/ffsb.sh
