os_type: centos   # xenial valgrind buggy, see http://tracker.zbkc.com/issues/18126
tasks:
- install:
    flavor: notcmalloc
    debuginfo: true
- zbkc:
- rgw:
    client.0:
      valgrind: [--tool=memcheck]
- swift:
    client.0:
      rgw_server: client.0
