os_type: centos   # xenial valgrind buggy, see http://tracker.zbkc.com/issues/18126
tasks:
- install:
    flavor: notcmalloc
    debuginfo: true
- zbkc:
- rgw:
    client.0:
      valgrind: [--tool=memcheck]
- s3tests:
    client.0:
      force-branch: zbkc-master
      rgw_server: client.0
overrides:
  zbkc:
    conf:
      global:
        osd_min_pg_log_entries: 10
        osd_max_pg_log_entries: 10
      client:
        rgw lc debug interval: 10
