tasks:
- install:
- zbkc:
- rgw: [client.0]
- s3tests:
    client.0:
      force-branch: zbkc-master
      rgw_server: client.0
overrides:
  zbkc:
    conf:
      client:
        rgw lc debug interval: 10
