tasks:
- install:
- zbkc:
    fs: xfs
    conf:
      mds:
        debug mds: 20
        debug ms: 1
      client:
        debug client: 20
        debug ms: 1
        fuse default permissions: false
        fuse set user groups: true
- zbkc-fuse:
- workunit:
    clients:
      all:
        - suites/pjd.sh
