
overrides:
  zbkc:
    conf:
      global:
        ms type: simple
    log-whitelist:
      - client session with invalid root

tasks:
  - zbkcfs_test_runner:
      modules:
        - tasks.zbkcfs.test_sessionmap
