tasks:
- install:
- zbkc:
    log-whitelist:
    - wrongly marked me down
    - objects unfound and apparently lost
    conf:
      osd:
        osd debug reject backfill probability: .3
        osd scrub min interval: 60
        osd scrub max interval: 120
        osd max backfills: 2
- thrashosds:
    timeout: 1200
    chance_pgnum_grow: 1
    chance_pgpnum_fix: 1
    min_in: 4
