overrides:
  zbkc:
    log-whitelist:
    - reached quota
    - wrongly marked me down
tasks:
- install:
- zbkc:
- workunit:
    clients:
      client.0:
        - rados/test.sh
        - rados/test_pool_quota.sh

