
# The task interferes with the network, so we need
# to permit OSDs to complain about that.
overrides:
  zbkc:
    log-whitelist:
      - wrongly marked me down
      - slow request

tasks:
  - zbkcfs_test_runner:
      modules:
        - tasks.zbkcfs.test_client_recovery
