
overrides:
  zbkc:
    log-whitelist:
      - inode wrongly marked free
      - bad backtrace on inode
      - inode table repaired for inode
      - Scrub error on inode

tasks:
  - zbkcfs_test_runner:
      modules:
        - tasks.zbkcfs.test_forward_scrub
